name: Deploy AlgoBot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/Discord_Algorthms_StudyBot
            git pull origin master
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 restart study-bot --update-env || pm2 start venv/bin/python --name "study-bot" -- main.py
            pm2 save