name: Deploy AlgoBot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 오라클 서버 접속 및 봇 업데이트
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/Discord_Algorthms_StudyBot
            git pull origin master

            # 의존성 갱신
            source venv/bin/activate
            pip install -r requirements.txt

            # 봇 재시작 또는 최초 실행
            pm2 restart study-bot --update-env || pm2 start /home/ubuntu/Discord_Algorthms_StudyBot/venv/bin/python3 --name "study-bot" -- main.py

            pm2 save
            exit 0